### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by kalitas** [card-io/card.io-iOS-source#10]
is it possible to use your lib without any validations? just use it as a card reader scan or manually entry without validations...
you made it very hard use your open source files :(

**Comment by dgoldman-ebay** [comment]
@kalitas the library was designed to handle five major credit cards, which is why the validations (Luhn checksum, overall length) are there. Changing that now is certainly a possibility, although not currently one that is high on our list of priorities.

> you made it very hard use your open source files :(

Sorry about that! As explained elsewhere, the library was not originally designed to be an open-source project, and so it will indeed take some work for a newcomer to figure things out and make changes. But we'll be happy to help out as we can, via discussions here in the github issues.
