### ISSUE TITLE
Size of generated libCardIO.a is too large (155.9 MB).

### ISSUE THREAD

**Issue by epiphany27** [card-io/card.io-iOS-source#25]
After building the project in XCode, the generated libCardIO.a in the Product folder of DerivedData is too large (155.9MB), while the static library in https://github.com/card-io/card.io-iOS-SDK/tree/master/CardIO is only 13.8MB.

How do I properly generate the static library? What am I missing here?

Thanks!

**Comment by dgoldman-ebay** [comment]
@pandeyGitHub did you try [this](https://github.com/card-io/card.io-iOS-source#unofficial-cardio-ios-sdk-release)?

**Comment by dgoldman-ebay** [comment]
@pandeyGitHub did you try the [instructions for "Unofficial card.io-iOS-SDK release"](https://github.com/card-io/card.io-iOS-source#unofficial-cardio-ios-sdk-release)?

**Comment by pandeyGitHub** [comment]
Thanks for the response.
As per your suggestion I tried running --> fab build:outdir=~ . I get the following error.

$ fab verbose build:outdir=~

[localhost] local: xcode-select -p
Setup
All *.strings files appear to be correct.
Will save release sdk to /Users/Pandey
[localhost] local: git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty

Fatal error: local() encountered an error (return code 128) while executing 'git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty'

Aborting.
local() encountered an error (return code 128) while executing 'git describe --match='iOS_[0-9]*.[0-9]*' --tags --always --dirty'

**Comment by dgoldman-ebay** [comment]
@pandeyGitHub try entering that `git describe...` command directly on the command line yourself. Hopefully this will produce a more detailed error message that will help point to the source of the problem.

**Comment by pandeyGitHub** [comment]
@dgoldman-ebay 
Thanks!
*  It's working now.  I tried _git describe..._ command as suggested by you but it didn't work because I was not using the **cloned** version of the repo. I had directly downloaded the card.io-iOS-source.zip file. So I cloned the repo into my machine henceforth. And everything seemed to work out fine.

*  One more question though. I'm trying to modify the project to suit my own needs. When I add new Classes in the card.io-iOS-source project, and use the generated libCardIO.a in my own separate SampleApp, I'm getting the linker error, during the build process of my SampleApp.

       Undefined symbols for architecture arm64:
       "_OBJC_CLASS_$_TestViewController", referenced from:
      objc-class-ref in HomeViewController.o
      ld: symbol(s) not found for architecture arm64
      clang: error: linker command failed with exit code 1 (use -v to see invocation).

      On the other hand, when I generate the libCardIO.a doing a normal build (from XCode IDE) instead, I'm able to build and use the static library without any such linker error issues. What could be the problem?

**Comment by dgoldman-ebay** [comment]
@pandeyGitHub When building a release version of card.io, we do a moderate amount of finicky work to limit the number of symbols which the library exposes. This is because card.io uses the OpenCV library, which resulted in symbol conflicts for developers whose apps independently included OpenCV.

The symbols which are to be publicly exposed are listed in the file `CardIO_exported_symbols.txt`.

I think that your problem might be solved if you add `OBJC_CLASS$_TestViewController` to that file. (You might need a leading underscore character, as with the other symbols already listed in the file. Experiment and learn! :smile_cat:)
