### ISSUE TITLE
card.io-lite

### ISSUE THREAD

**Issue by jeffchang** [card-io/card.io-iOS-source#27]
Quick question -- any chance you'd be up for creating a lite version of card.io? :smile: 

We're happily using card.io in our app, but with the latest card.io, it accounts for 40% of the size of our app download (2.5 of 6.3MB).  Small app size is key for our product, since it's most often downloaded when time is really tight.

How tough would it be to strip out the "enter manually" view and remove the AudioToolbox framework?  Are there any other crafty revisions you can think of, that might shrink card.io's footprint a bit further?

Thanks so much!

**Comment by burnto** [comment]
Thanks for this feedback. 

AudioToolbox, being a system framework, is dynamically linked, so really doesn't add to the size of your app. 

Have you tried using the [CardIOView](https://github.com/card-io/card.io-iOS-source/blob/master/CardIO_Public_API/CardIOView.h) class directly? Minus a few assets and strings files, this is the minimal card.io functionality and, if using this, your linker shouldn't pull in the manual entry view. I'm not sure how much this will actually help, but thought it worth mentioning as worth experimentation. 

My guess is that some of the heft also comes from image and strings assets, which are encoded at library compile time via Baler (rather than included in a separate single resource bundle) and thus are duplicated per architecture. So you could try a custom build yourself with some of these assets removed. 

I don't think the team has the bandwidth for a lite project right now, but of course "pull requests welcome" as always. 

Hope this helps.

**Comment by dgoldman-ebay** [comment]
To add to @burnto's information, probably the biggest component of card.io's size are the "models" that represent the machine learning networks that are used to decipher the card number and expiration date. IIRC, these comprise a couple of megabytes. It will therefore be challenging to significantly decrease card.io's size while still retaining its core functionality.

**Comment by josharian** [comment]
I poked through the binary a bit, and @burnto's suspicion is confirmed: Far and away the largest non-computer-vision component is the baler bundle, weighing in at ~123k (if nm is to be believed).

**Comment by regosen** [comment]
For now our team is sticking with card.io v3.10.0 instead of switching to latest (v5.0.6) because it added another 1MB to our binary size.

Given what I'm reading here, it sounds like most of that 1MB change should be related to the "computer-vision component", but we tried scanning several cards using both versions and didn't notice a difference in scanning success rate or the amount of time it takes to capture the card.

What does v5 give us over v3 in return for the additional 1MB?

**Comment by dgoldman-ebay** [comment]
@regosen from the [release notes](https://github.com/card-io/card.io-iOS-source/blob/master/Release/release_notes.txt):
```
5.0.0 (Tue 1/20/2015)

* Add automatic expiry-scanning.
  You can disable this feature via the new `scanExpiry` property of either CardIOView or CardIOPaymentViewController.
  Note: Expiry scans will not infrequently fail to obtain the correct expiry date.
        We are continuing to work to improve expiry-scanning accuracy.
```

**Comment by regosen** [comment]
Fair enough.  :)
