### ISSUE TITLE
ln: .git/hooks/pre-commit: No such file or directory

### ISSUE THREAD

**Issue by invmobiledev** [card-io/card.io-iOS-source#8]
Hi,
I am trying to run the sample xcode project provided and facing this issue "ln: .git/hooks/pre-commit: No such file or directory".

From this link - https://github.com/cyassl/cyassl/issues/26, it seems like this issue arises due to 'a git download without .git directory structure'.

Requesting you to please help me resolve this issue.

**Comment by dgoldman-ebay** [comment]
@invmobiledev we'll try to get this fixed quickly for you.

Did you obtain your local copy of card.io-iOS-source by cloning the repo, or by downloading the zip file?

**Comment by dgoldman-ebay** [comment]
@invmobiledev I think that my latest commit should fix your problem. Please re-open this issue if not.

**Comment by invmobiledev** [comment]
Hi @dgoldman-ebay . 

Thank you for your prompt response. I apologize in advance because i am not too experienced with these sort of issues. I downloaded the latest commit of code.io and am facing the following issue now

Check setup instructions: .baler_env is missing
Command /bin/sh failed with exit code 1.

![screen shot 2015-01-13 at 7 37 17 pm](https://cloud.githubusercontent.com/assets/8523046/5721738/114e8ffc-9b5b-11e4-92b3-a2cfeae250b7.png)
.

Requesting your help on this one.

**Comment by dgoldman-ebay** [comment]
@invmobiledev the relevant setup instructions are [these](https://github.com/card-io/card.io-iOS-source#python) (the `pip install` command) and [these](https://github.com/card-io/card.io-iOS-source#baler) specifically regarding `.baler_env`.

**Comment by burnto** [comment]
@dgoldman-ebay I wonder if we should try to skip the baler step if `.baler_env` is not present.

**Comment by dgoldman-ebay** [comment]
@burnto interesting idea! So if no `.baler_env`, then behave as if all strings and graphic assets have remained unchanged?

**Comment by burnto** [comment]
Yeah, since most folks won't want to mess with baler. We may want to just remove it altogether.

Note that for images, we've been [using vectors](https://github.com/braintree/braintree_ios/tree/master/Braintree/UI/Views/Vector%20Art) in the braintree iOS SDK (using [PaintCode](http://www.paintcodeapp.com/) to generate the drawing code) and it's been quite lovely. So a similar approach could be used here to eliminate the few images. Not sure how to best bundle up the strings files, but maybe some simpler codegen step?

If/when we ever get this project converted to a CocoaPod or similar, we can use [resource bundles](http://guides.cocoapods.org/syntax/podspec.html#resource_bundles).

**Comment by dgoldman-ebay** [comment]
@invmobiledev based on @burnto's suggestion, the latest commit should now allow you to proceed without worrying about Baler.

**Comment by invmobiledev** [comment]
Hi @dgoldman-ebay. Thank you again. I am no longer facing the previously reported issue. However, seems like a lot of resource files are missing. Please find the screenshot below.


![screen shot 2015-01-14 at 10 03 25 am](https://cloud.githubusercontent.com/assets/8523046/5734114/d9d3a006-9bd4-11e4-8508-6adea379d33f.png)

The Sample project fails to run because of this. I checked the directory folders as well and see that file are not present there as well.

![screen shot 2015-01-14 at 10 06 21 am](https://cloud.githubusercontent.com/assets/8523046/5734100/968caa90-9bd4-11e4-8819-30043c947590.png)

**Comment by dgoldman-ebay** [comment]
@invmobiledev you need to try to work through the [installation instructions](https://github.com/card-io/card.io-iOS-source#cardio-dmz).

And for our part, we will need to make those instructions more clear and explicit.

I would suggest that you start over. Rather than downloading a zip file of this archive, you should [use git to *clone* this repository, including its `dmz` submodule](https://github.com/card-io/card.io-iOS-source#dev-setup).

**Comment by invmobiledev** [comment]
Thank you @dgoldman-ebay . I was able to get the sample project to work by downloading the dmz files and adding the same. Sorry for pestering you repeatedly with issues.. :-)

Maybe an unrelated question, i was hoping this version would scan the expiry number along with the card number. However, i noticed that expiry details need to be entered by the user after card number scan. Is this as per design? or is card expiry details not working for me?

**Comment by dgoldman-ebay** [comment]
@invmobiledev good work figuring out the dmz issue! Great that you were able to build and run the sample project.

Work on expiry-scanning is happening on the [`feature/expiry` branch of this repo](https://github.com/card-io/card.io-iOS-source/tree/feature/expiry). (Along with the [`feature/expiry` branch of the `dmz` repo](https://github.com/card-io/card.io-dmz/tree/feature/expiry)). This is currently a work-in-progress, although I hope to release an official first beta version within the next week or two.

**Comment by invmobiledev** [comment]
@dgoldman-ebay Thank you for all the guidance. Card expiry details scanning is working neatly for me. I will check back again in a couple of weeks as per your comments.

**Comment by dgoldman-ebay** [comment]
Thanks for the feedback, @invmobiledev! It's encouraging to hear that the expiry-scanning is already working for you. I hope to improve it a bit more before (soon) officially making it a part of card.io.
